.PHONY: clean All

All:
	@echo "----------Building project:[ Project-02 - Debug ]----------"
	@cd "Project-02" && "$(MAKE)" -f  "Project-02.mk"
clean:
	@echo "----------Cleaning project:[ Project-02 - Debug ]----------"
	@cd "Project-02" && "$(MAKE)" -f  "Project-02.mk" clean
