.PHONY: clean All

All:
	@echo "----------Building project:[ 34-Section-Challenge - Debug ]----------"
	@cd "34-Section-Challenge" && "$(MAKE)" -f  "34-Section-Challenge.mk"
clean:
	@echo "----------Cleaning project:[ 34-Section-Challenge - Debug ]----------"
	@cd "34-Section-Challenge" && "$(MAKE)" -f  "34-Section-Challenge.mk" clean
