.PHONY: clean All

All:
	@echo "----------Building project:[ 29-What-Are-Compiler-Errors - Debug ]----------"
	@cd "29-What-Are-Compiler-Errors" && "$(MAKE)" -f  "29-What-Are-Compiler-Errors.mk"
clean:
	@echo "----------Cleaning project:[ 29-What-Are-Compiler-Errors - Debug ]----------"
	@cd "29-What-Are-Compiler-Errors" && "$(MAKE)" -f  "29-What-Are-Compiler-Errors.mk" clean
